
font_family CaskaydiaCove Nerd Font
font_size 10
window_padding_width 25


# BEGIN_KITTY_THEME
# Gruvbox Dark Soft
background_opacity 0.4
background_blur 1
include current-theme.conf
# END_KITTY_THEME
